### ISSUE TITLE
Does not build with Python 3.6.2

### ISSUE THREAD

**Issue by stefanos82** [danrobinson/taggernews#3]
I guess it's because you are using modules, like BeautifulSoup 3.2.1 that has been discontinued and works with versions <= to Python 2.7?

**Comment by dodger487** [comment]
Yeah, I think the hard requirement that has us stuck on Python 2.7 is the package `goose`. We ended up running our topic modeling on data processed with goose, and therefore we wanted to keep using goose in production when we apply the model, so it's a little hard to step away from that dependency. I think we'll just leave this issue open for now in case someone figures out a good way to make this run on 3+
