### ISSUE TITLE
Article time is incorrect

### ISSUE THREAD

**Issue by tomglynch** [danrobinson/taggernews#8]
Hi David, I've been using taggernews for a while to keep on top of blockchain tech news. Recently, it has not been updating to reflect recent articles, and the times listed on articles is incorrect. 

I was going to have a poke around myself but having some issues getting all requirements installed, so thought I'd just drop a message here for you to have a quick look if it's an easy fix before I proceed.

Any ideas? 

It's a ripper product and I love it! 

Thanks,

Tom

**Comment by tomglynch** [comment]
Bumping this thread, @danrobinson

**Comment by danrobinson** [comment]
Hey @tomglynch! taggernews.com is finally back online (just had to reset its database; something filled up), so I think this issue is resolved; let me know if you have any more problems.

**Comment by tomglynch** [comment]
Thought that it might be something simple like that! Thanks so much for
fixing - it's a fantastic tool!

Tom

**Comment by tomglynch** [comment]
Think it's having similar or different issues again

**Comment by danrobinson** [comment]
Seems fine to me?

**Comment by tomglynch** [comment]
If you go to a subsection (in this case
http://www.taggernews.com/tags/blockchain/), post 6. The crypto alternative
says 6 hours ago but was actually 2 day ago, and post 27. On Radical
Markets - it says 4 hours ago but it is 21 days ago, see here:
https://news.ycombinator.com/item?id=16907064



Is this reproducible for you?

**Comment by tomglynch** [comment]
I think this line: https://github.com/danrobinson/taggernews/blob/f3344b2fb573126f54214cfbf9a42130dcfc4b45/articles/management/commands/refresh_top_articles.py#L65

Creates a timestamp but I don't think there is an update of current time vs that time afterwards?

**Comment by ngould** [comment]
Looks like the problem is in the `age` method on the `Article` model. It should use `delta.total_seconds()` instead of `delta.seconds`, which gives the second difference modulo one day.

**Comment by ngould** [comment]
@tomglynch Want to do the honors?

**Comment by tomglynch** [comment]
Just looking in pull requests, found it done already: 

https://github.com/danrobinson/taggernews/pull/5/commits/b7bc509a154894fe316ed0b3cf3b0cc4216bf6f7
